FROM python:3.10

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    awscli \
    && rm -rf /var/lib/apt/lists/*

RUN pip install dvc

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]




