version: '3'

services:
  train:
    build:
      context: .
      dockerfile: dockerfile_train
    volumes:
      - ./src/training:/app/src/training

  flask:
    build:
      context: .
      dockerfile: dockerfile_flask
    ports: 
      - "5000:5000"
    depends_on:
      - train
    volumes:
      - ./src/training:/app/src/training

  test:
    build:
      context: .
      dockerfile: dockerfile_test
    depends_on:
      - flask
