version: '3'

services:
  mlflow-experiment:
    build:
      context: .
      dockerfile: Dockerfile_pipeline
    volumes:
      - ./train.py:/app/train.py  
      - ./iris_artifacts:/app/iris_artifacts  
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000 
    depends_on:
      - mlflow-server

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    ports:
      - "5000:5000"  
